### ISSUE TITLE
Proposal: Renaming to Client-Only

### ISSUE THREAD

**Issue by Atinux** [egoist/vue-client-only#20]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/vue-no-ssr/issues/20)

Hey there,

As you know, we are using `<no-ssr>` in Nuxt.js and after looking at this PR (https://github.com/nuxt/nuxt.js/pull/5941), I do believe the right naming should be `<client-only>`.

I know that VuePress actually uses this naming as well: https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions

What do you think?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/vue-no-ssr/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by egoist** [comment]
Yeah I'll probably rename this project to `vue-client-only` as well.

**Comment by Atinux** [comment]
@egoist shouldn't be better to also rename the repo + book the npm package `https://www.npmjs.com/package/vue-client-only` also?

**Comment by egoist** [comment]
@Atinux 👌

**Comment by Atinux** [comment]
I suggest:
- `1.x` branch for `vue-no-ssr`
- `master` branch for `vue-client-only` + note on `1.x` branch for `vue-no-ssr`
- Renaming repo to `vue-client-only`+ publish `master` with version `v2.0.0`

WDYT?

**Comment by egoist** [comment]
LGTM, just created [1.x branch](https://github.com/egoist/vue-no-ssr/tree/1.x)
