### ISSUE TITLE
Is this in Nuxt core... or ?

### ISSUE THREAD

**Issue by TheMangoTrain** [egoist/vue-client-only#88]
Does this package still need to be explicitly installed, or is it in Nuxt core?

Looking at Nuxt official docs, one could mistake it being Nuxt core...
https://nuxtjs.org/api/components-client-only
or
https://nuxtjs.org/guides/features/nuxt-components#the-client-only-component

**Comment by manniL** [comment]
It is automatically included by Nuxt.

**Comment by kissu** [comment]
Here is the link on the documentation: https://nuxtjs.org/docs/2.x/features/nuxt-components#the-client-only-component
